name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: compile game
      run: make compile-game
    - name: run unit tests
      run: make run-tests
    - name: lint
      uses: make lint

  windows:

    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install make
      - name: compile game
        run: make compile-game
      - name: run unit tests
        run: make run-tests
      - name: lint
      uses: make lint

