name: CI pipeline

on:
  push:
    branches: [ "main_ubuntu" ]
  pull_request:
    branches: [ "main_ubuntu" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: compile game
      run: make compile-game
    - name: run unit tests
      run: make run-tests
