name: CI pipeline

on:
  push:
    branches: 
      - main-ubuntu
  pull_request:
    branches: 
      - main-ubuntu

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: "main-ubuntu"
    - name: compile game
      run: make compile-game
    - name: run unit tests
      run: make run-tests
